declare const p5pkg: any;

window.addEventListener('load', function () {
  const script = document.querySelector('script[type="text/perl"]');
  const source = script?.innerHTML;
  const compiled = !source
    ? ''
    : p5pkg.Perlito5.compile_p5_to_js([source]).replace(
        'Do not edit this file - Generated by Perlito5',
        'Generated by Perlito5',
      );
  // eslint-disable-next-line no-eval
  eval(compiled);
  parent.postMessage({ type: 'compiled', payload: { language: 'perl', content: compiled } }, '*');
});
