import { LanguageSpecs } from '../models';
import { vendorsBaseUrl } from '../vendors';

export const perl: LanguageSpecs = {
  name: 'perl',
  title: 'Perl',
  compiler: {
    factory: () => async (code) => code,
    scripts: [vendorsBaseUrl + 'perlito/perlito5.min.js'],
    inlineScript: `
    window.addEventListener('load', function() {
      var script = document.querySelector('script[type="text/perl"]');
      var source = script.innerHTML;
      var compiled = p5pkg.Perlito5.compile_p5_to_js([source]).replace(
        'Do not edit this file - Generated by Perlito5',
        'Generated by Perlito5',
      )
      eval(compiled);
      parent.postMessage({type: 'compiled', payload: {language: 'perl', content: compiled}}, '*');
    });
    `,
    scriptType: 'text/perl',
  },
  extensions: ['pl', 'pm'],
  editor: 'script',
};
