import { LanguageSpecs } from '../models';

export const perl: LanguageSpecs = {
  name: 'perl',
  title: 'Perl',
  compiler: {
    url: 'assets/noop.js',
    factory: () => (code) => code,
    umd: true,
    scripts: ['vendor/perlito/perlito5.min.js'],
    inlineScript: `
    window.addEventListener('load', () => {
      let js = '';
      document.querySelectorAll('script[type="text/perl"]').forEach(script => {
        const source = script.innerHTML;
        const compiled = p5pkg.Perlito5.compile_p5_to_js([source]).replace(
          'Do not edit this file - Generated by Perlito5',
          'Generated by Perlito5',
        )
        js = js === '' ? compiled : js + '\\n' + compiled;
      });
      eval(js);
      parent.postMessage({type: 'compiled', payload: {language: 'perl', content: js}}, '*');
    });
    `,
    scriptType: 'text/perl',
  },
  extensions: ['pl', 'pm'],
  editor: 'script',
};
