import { LanguageSpecs } from '../models';

export const perl: LanguageSpecs = {
  name: 'perl',
  title: 'Perl',
  info: `
  <h3>Perl</h3>
  <div>Perl running in the browser using Perlito.</div>
  <ul>
    <li><a href="https://www.perl.org/" target="_blank">Perl official website</a></li>
    <li><a href="https://perldoc.perl.org/" target="_blank">Perl documentation</a></li>
    <li><a href="https://github.com/fglock/Perlito/blob/master/README-perlito5.md" target="_blank">Perlito5 Readme</a></li>
    <!-- <li><a href="#">Perl usage in LocalPen</a></li> -->
    <li><a href="?template=perl" target="_parent" data-template="perl">Load starter template</a></li>
  </ul>
  `,
  compiler: {
    url: 'assets/noop.js',
    factory: () => (code) => code,
    umd: true,
    scripts: ['vendor/perlito/perlito5.min.js'],
    inlineScript: `
    window.addEventListener('load', () => {
      let js = '';
      document.querySelectorAll('script[type="text/perl"]').forEach(script => {
        const source = script.innerHTML;
        const compiled = p5pkg.Perlito5.compile_p5_to_js([source]).replace(
          'Do not edit this file - Generated by Perlito5',
          'Generated by Perlito5',
        )
        js = js === '' ? compiled : js + '\\n' + compiled;
      });
      eval(js);
      parent.postMessage({type: 'compiled', payload: {language: 'perl', content: js}}, '*');
    });
    `,
    scriptType: 'text/perl',
  },
  extensions: ['pl', 'pm'],
  editor: 'script',
};
