import type { StoryDef } from '../../common';

const storyDef: StoryDef = {
  Blank: { props: { template: 'blank' } },
  JavaScript: { props: { template: 'javascript' }, storyName: 'JavaScript' },
  TypeScript: { props: { template: 'typescript' }, storyName: 'TypeScript' },
  React: { props: { template: 'react' } },
  ReactNative: { props: { template: 'react-native' } },
  Vue3: { props: { template: 'vue' } },
  Angular: { props: { template: 'angular' } },
  Preact: { props: { template: 'preact' } },
  Svelte: { props: { template: 'svelte' } },
  Solid: { props: { template: 'solid' } },
  Lit: { props: { template: 'lit' } },
  Stencil: { props: { template: 'stencil' } },
  Markdown: { props: { template: 'markdown' } },
  MDX: { props: { template: 'mdx' } },
  TailwindCSS: { props: { template: 'tailwindcss' } },
  ShadcnUI: { props: { template: 'shadcn-ui' } },
  DaisyUI: { props: { template: 'daisyui' } },
  Bootstrap: { props: { template: 'bootstrap' } },
  Astro: { props: { template: 'astro' } },
  Riotjs: { props: { template: 'riot' } },
  Malinajs: { props: { template: 'malina' } },
  JQuery: { props: { template: 'jquery' }, storyName: 'jQuery' },
  Backbone: { props: { template: 'backbone' } },
  Knockout: { props: { template: 'knockout' } },
  Jest: { props: { template: 'jest' } },
  JestReact: { props: { template: 'jest-react' } },
  D3: { props: { template: 'd3' } },
  Phaser: { props: { template: 'phaser' } },
  Vue2: { props: { template: 'vue2' } },
  CoffeeScript: { props: { template: 'coffeescript' }, storyName: 'CoffeeScript' },
  LiveScript: { props: { template: 'livescript' }, storyName: 'LiveScript' },
  Civet: { props: { template: 'civet' } },
  Clio: { props: { template: 'clio' } },
  Imba: { props: { template: 'imba' } },
  Elm: { props: { template: 'elm' } },
  ReScript: { props: { template: 'rescript' }, storyName: 'ReScript' },
  Reason: { props: { template: 'reason' } },
  Ocaml: { props: { template: 'ocaml' } },
  Python: { props: { template: 'python' } },
  PythonWasm: { props: { template: 'python-wasm' } },
  R: { props: { template: 'r' } },
  Ruby: { props: { template: 'ruby' } },
  Go: { props: { template: 'go' } },
  GoWasm: { props: { template: 'go-wasm' } },
  PHP: { props: { template: 'php' } },
  PHPWasm: { props: { template: 'php-wasm' }, storyName: 'PHP Wasm' },
  Cpp: { props: { template: 'cpp' } },
  CWasm: { props: { template: 'c-wasm' } },
  CppWasm: { props: { template: 'cpp-wasm' } },
  ObjcWasm: { props: { template: 'objc-wasm' } },
  RustWasm: { props: { template: 'rust-wasm' } },
  ZigWasm: { props: { template: 'zig-wasm' } },
  Java: { props: { template: 'java' } },
  CSharpWasm: { props: { template: 'csharp-wasm' } },
  VbWasm: { props: { template: 'vb-wasm' } },
  FSharp: { props: { template: 'fsharp' } },
  FSharpWasm: { props: { template: 'fsharp-wasm' } },
  Haskell: { props: { template: 'haskell' } },
  HaskellWasm: { props: { template: 'haskell-wasm' } },
  Scheme: { props: { template: 'scheme' } },
  CommonLisp: { props: { template: 'commonlisp' } },
  ClojureScript: { props: { template: 'clojurescript' }, storyName: 'ClojureScript' },
  Perl: { props: { template: 'perl' } },
  Lua: { props: { template: 'lua' } },
  LuaWasm: { props: { template: 'lua-wasm' } },
  Teal: { props: { template: 'teal' } },
  Fennel: { props: { template: 'fennel' } },
  Julia: { props: { template: 'julia' } },
  Tcl: { props: { template: 'tcl' } },
  AssemblyScript: { props: { template: 'assemblyscript' }, storyName: 'AssemblyScript' },
  WebAssemblyText: { props: { template: 'wat' }, storyName: 'WebAssembly Text' },
  SQL: { props: { template: 'sql' } },
  PostgreSQL: { props: { template: 'postgresql' } },
  Prolog: { props: { template: 'prolog' } },
  Minizinc: { props: { template: 'minizinc' } },
  Blockly: { props: { template: 'blockly' } },
  Diagrams: { props: { template: 'diagrams' } },
};

export default storyDef;
