import type { StoryDef } from '../../common';

const storyDef: StoryDef = {
  Blank: { props: { template: 'blank' } },
  JavaScript: { props: { template: 'javascript' }, storyName: 'JavaScript' },
  TypeScript: { props: { template: 'typescript' }, storyName: 'TypeScript' },
  React: { props: { template: 'react' } },
  ReactNative: { props: { template: 'react-native' } },
  Vue2: { props: { template: 'vue2' } },
  Vue3: { props: { template: 'vue' } },
  Angular: { props: { template: 'angular' } },
  Preact: { props: { template: 'preact' } },
  Svelte: { props: { template: 'svelte' } },
  Stencil: { props: { template: 'stencil' } },
  Solid: { props: { template: 'solid' } },
  MDX: { props: { template: 'mdx' } },
  Astro: { props: { template: 'astro' } },
  Riotjs: { props: { template: 'riot' } },
  Malinajs: { props: { template: 'malina' } },
  JQuery: { props: { template: 'jquery' }, storyName: 'jQuery' },
  Backbone: { props: { template: 'backbone' } },
  Knockout: { props: { template: 'knockout' } },
  Jest: { props: { template: 'jest' } },
  JestReact: { props: { template: 'jest-react' } },
  Bootstrap: { props: { template: 'bootstrap' } },
  TailwindCSS: { props: { template: 'tailwindcss' } },
  CoffeeScript: { props: { template: 'coffeescript' }, storyName: 'CoffeeScript' },
  LiveScript: { props: { template: 'livescript' }, storyName: 'LiveScript' },
  Civet: { props: { template: 'civet' } },
  Clio: { props: { template: 'clio' } },
  Imba: { props: { template: 'imba' } },
  ReScript: { props: { template: 'rescript' }, storyName: 'ReScript' },
  Reason: { props: { template: 'reason' } },
  Ocaml: { props: { template: 'ocaml' } },
  Python: { props: { template: 'python' } },
  PythonPyodide: { props: { template: 'python-wasm' } },
  R: { props: { template: 'r' } },
  Ruby: { props: { template: 'ruby' } },
  Go: { props: { template: 'go' } },
  PHP: { props: { template: 'php' } },
  Cpp: { props: { template: 'cpp' } },
  CppClang: { props: { template: 'cpp-wasm' } },
  Perl: { props: { template: 'perl' } },
  Lua: { props: { template: 'lua' } },
  Teal: { props: { template: 'teal' } },
  Fennel: { props: { template: 'fennel' } },
  Julia: { props: { template: 'julia' } },
  Scheme: { props: { template: 'scheme' } },
  CommonLisp: { props: { template: 'commonlisp' } },
  ClojureScript: { props: { template: 'clojurescript' }, storyName: 'ClojureScript' },
  Tcl: { props: { template: 'tcl' } },
  Markdown: { props: { template: 'markdown' } },
  AssemblyScript: { props: { template: 'assemblyscript' }, storyName: 'AssemblyScript' },
  WebAssemblyText: { props: { template: 'wat' }, storyName: 'WebAssembly Text' },
  SQL: { props: { template: 'sql' } },
  Prolog: { props: { template: 'prolog' } },
  Blockly: { props: { template: 'blockly' } },
  Diagram: { props: { template: 'diagrams' } },
};

export default storyDef;
