import { LokaliseApi } from '@lokalise/node-api';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import prettier from 'prettier';
import { exit } from 'process';
import { autoGeneratedWarning, prettierConfig, sortedJSONify } from './i18n-export.js';

const outDir = path.resolve('src/livecodes/i18n/locales');
const tmpDir = path.join(outDir, 'tmp');
const api = new LokaliseApi({
  apiKey: process.env.LOKALISE_API_TOKEN,
});
const projectID = process.env.LOKALISE_PROJECT_ID;

const namespaces = ['translation', 'language-info'];

const namespaceConfig = {
  translation: { name: 'translation', type: 'I18nTranslation' },
  'language-info': { name: 'languageInfo', type: 'I18nLangInfoTranslation' },
};

const fileExists = async (file) => {
  try {
    await fs.promises.access(file);
    return true;
  } catch {
    return false;
  }
};

/**
 * Read a Lokalise JSON file into a flat `key -> translation` map.
 * The `$comment` attribute is skipped and Lokalise's `tag-N` placeholder prefix is removed.
 * @param {string} file Path to the `.lokalise.json` file.
 * @returns {Promise<Record<string, string>>}
 */
const readTranslations = async (file) => {
  /** @type {{[s: string]: {translation: string}}} */
  const content = JSON.parse(await fs.promises.readFile(file, 'utf-8'));
  const translations = {};
  for (const key in content) {
    if (key === '$comment') {
      continue;
    }
    translations[key] = String(content[key].translation).replace(/<(\/?)tag-(\d+)>/g, '<$1$2>');
  }
  return translations;
};

/**
 * Expand a flattened translation object (KV pairs) to a nested object.
 * @param {Record<string, string>} translations Flat translation object.
 * @returns Record<string, unknown>
 */
const nestTranslationObject = (translations) => {
  const translationObject = {};
  for (const key in translations) {
    const keys = key.split('.');
    const lastKey = keys.pop();
    let currentObject = translationObject;
    keys.forEach((k) => {
      if (!currentObject[k]) {
        currentObject[k] = {};
      }
      currentObject = currentObject[k];
    });
    currentObject[lastKey] = translations[key];
  }
  return translationObject;
};

const importFromLokalise = async () => {
  const ciMode = process.env.CI === 'true';
  const forceLocalMode = process.argv.slice(2).includes('--force');
  const useLocalResourcesMode = process.argv.slice(2).includes('--local');

  if (!ciMode && !forceLocalMode) {
    console.error('This script is intended to be run in CI mode or with --force flag.');
    exit(1);
  }

  const branchName = process.argv[2];

  if (!branchName) {
    console.error('Branch name is required');
    exit(1);
  }

  // Make a tmp directory to store the downloaded files
  const lokaliseTempDir = path.resolve(process.env.LOKALISE_TEMP);

  if (!useLocalResourcesMode) {
    console.log('Fetching translations from Lokalise...');

    const fullProjectId = `${projectID}:${branchName}`;
    const process = await api.files().async_download(fullProjectId, {
      format: 'json',
      original_filenames: true,
      json_unescaped_slashes: true,
      replace_breaks: false,
      placeholder_format: 'i18n',
      // Omit untranslated keys so they can fall back to the existing translation in the repository.
      export_empty_as: 'skip',
    });

    // Wait until process is finished
    const timeout = 60000;
    const delay = 2500;
    const startTime = Date.now();

    /** @type {import("@lokalise/node-api").DownloadedFileProcessDetails} */
    let response;

    while (true) {
      const processInfo = await api
        .queuedProcesses()
        .get(process.process_id, { project_id: fullProjectId });

      if (processInfo.status === 'finished') {
        response = processInfo.details;
        break;
      }

      if (Date.now() - startTime > timeout) {
        console.error('Timeout exceeded. Aborting...');
        exit(1);
      }

      await new Promise((resolve) => setTimeout(resolve, delay));
    }

    console.log(`Downloading zip file from ${response.download_url}`);

    const zipPath = path.join(lokaliseTempDir, 'locales.zip');
    const zipFile = await fetch(response.download_url);
    await fs.promises.writeFile(zipPath, Buffer.from(await zipFile.arrayBuffer()));

    console.log(`Extracting zip file to ${lokaliseTempDir}...`);
    execSync(`unzip -o ${zipPath} -d ${lokaliseTempDir}`);
    await fs.promises.unlink(zipPath);
  }

  const languages = await fs.promises.readdir(lokaliseTempDir);
  console.log(
    `Extracted languages to tmp directory, ${languages.length} languages (including English) found.`,
  );

  console.log('Checking if translation keys are outdated...');

  /** @type {{[s: string]: Record<string, string>}} */
  const localTranslation = {};

  /** @type {{[s: string]: Record<string, string>}} */
  const lokaliseTranslation = {};

  // Read the local translation files as baseline
  execSync('npm run i18n-export -- --save-temp', { stdio: 'pipe' });
  const localNamespaces = (await fs.promises.readdir(tmpDir)).filter((file) =>
    file.endsWith('.lokalise.json'),
  );
  for (const file of localNamespaces) {
    const namespace = file.replace('.lokalise.json', '');
    localTranslation[namespace] = await readTranslations(path.join(tmpDir, file));
  }

  // Read current source on Lokalise
  const enPath = path.join(lokaliseTempDir, 'en');
  const enFiles = await fs.promises.readdir(enPath);
  for (const file of enFiles) {
    if (!file.endsWith('.lokalise.json')) {
      continue;
    }
    const namespace = file.replace('.lokalise.json', '');
    lokaliseTranslation[namespace] = await readTranslations(path.join(enPath, file));
  }

  // A key is outdated when the English source changed after the last upload to Lokalise.
  // Keys that are missing from Lokalise are kept, as the local English source is the source of truth.
  const outdatedKeys = {};
  for (const namespace of namespaces) {
    outdatedKeys[namespace] = new Set();
    const lokaliseEn = lokaliseTranslation[namespace] || {};
    for (const key of Object.keys(localTranslation[namespace] || {})) {
      const lokaliseValue = lokaliseEn[key];
      if (lokaliseValue !== undefined && lokaliseValue !== localTranslation[namespace][key]) {
        console.warn(`Deprecating outdated translation: Key ${key} in namespace ${namespace}.`);
        outdatedKeys[namespace].add(key);
      }
    }
  }

  // Lokalise may export duplicate files with a ` (n)` suffix (e.g. `translation.lokalise (15).json`).
  // These are not valid namespaces and should not be imported. Sweep the whole locales directory
  // (not just the languages in this download) to clean up any that were previously committed.
  const localeDirs = (await fs.promises.readdir(outDir)).filter((name) =>
    fs.statSync(path.join(outDir, name)).isDirectory(),
  );
  await Promise.all(
    localeDirs.map(async (locale) => {
      const localePath = path.join(outDir, locale);
      const strayFiles = (await fs.promises.readdir(localePath)).filter((file) =>
        /\.lokalise \(\d+\)\.json$/.test(file),
      );
      await Promise.all(strayFiles.map((file) => fs.promises.unlink(path.join(localePath, file))));
    }),
  );

  for (let language of languages) {
    const languagePath = path.join(lokaliseTempDir, language);
    if (!(await fs.promises.stat(languagePath)).isDirectory() || language === 'en') {
      continue;
    }

    language = language.replace(/_/g, '-');
    const outLanguagePath = path.join(outDir, language);
    console.log(`Importing language ${language}...`);

    await fs.promises.mkdir(outLanguagePath, { recursive: true });

    const files = (await fs.promises.readdir(languagePath)).filter((file) =>
      namespaces.includes(file.replace('.lokalise.json', '')),
    );

    const filePromises = files.map(async (file) => {
      const namespace = file.replace('.lokalise.json', '');
      const { name, type } = namespaceConfig[namespace];
      const target = path.join(outLanguagePath, `${namespace}.ts`);

      // Translations pulled from Lokalise for this language
      const pulled = await readTranslations(path.join(languagePath, file));

      // Existing translations in the repository, used as a fallback for keys
      // that are not returned by Lokalise (e.g. keys missing on a stale branch).
      const existingPath = path.join(outLanguagePath, `${namespace}.lokalise.json`);
      const existing = (await fileExists(existingPath)) ? await readTranslations(existingPath) : {};

      const merged = {};
      for (const key of Object.keys(localTranslation[namespace] || {})) {
        if (outdatedKeys[namespace].has(key)) {
          continue;
        }
        const value = pulled[key] ?? existing[key];
        if (value !== undefined) {
          merged[key] = value;
        }
      }

      const translationObject = nestTranslationObject(merged);
      const sortedTranslationObject = sortedJSONify(translationObject);
      const code = `${autoGeneratedWarning}

          import type { ${type} } from '../models';

          const ${name}: ${type} = ${sortedTranslationObject};

          export default ${name};
        `;

      const translationContent = await prettier.format(code, {
        parser: 'typescript',
        ...prettierConfig,
      });

      return fs.promises.writeFile(target, translationContent);
    });

    await Promise.all(filePromises);
  }
};

importFromLokalise();
