export const starterTemplates = {
  "blank": "Blank Project",
  "javascript": "JavaScript Starter",
  "typescript": "TypeScript Starter",
  "react": "React Starter",
  "react-native": "React Native Starter",
  "vue": "Vue SFC Starter",
  "angular": "Angular Starter",
  "preact": "Preact Starter",
  "svelte": "Svelte Starter",
  "solid": "Solid Starter",
  "lit": "Lit Starter",
  "stencil": "Stencil Starter",
  "mdx": "MDX Starter",
  "tailwindcss": "Tailwind CSS Starter",
  "shadcn-ui": "shadcn/ui Starter",
  "daisyui": "daisyUI Starter",
  "bootstrap": "Bootstrap Starter",
  "astro": "Astro Starter",
  "riot": "Riot.js Starter",
  "malina": "Malina.js Starter",
  "jquery": "jQuery Starter",
  "backbone": "Backbone Starter",
  "knockout": "Knockout Starter",
  "jest": "Jest Starter",
  "jest-react": "Jest/React Starter",
  "d3": "D3 Starter",
  "phaser": "Phaser Starter",
  "vue2": "Vue 2 Starter",
  "coffeescript": "CoffeeScript Starter",
  "livescript": "LiveScript Starter",
  "civet": "Civet Starter",
  "clio": "Clio Starter",
  "imba": "Imba Starter",
  "rescript": "ReScript Starter",
  "reason": "Reason Starter",
  "ocaml": "Ocaml Starter",
  "python": "Python Starter",
  "python-wasm": "Python (Wasm) Starter",
  "r": "R Starter",
  "ruby": "Ruby Starter",
  "ruby-wasm": "Ruby (Wasm) Starter",
  "go": "Go Starter",
  "go-wasm": "Go (Wasm) Starter",
  "php": "PHP Starter",
  "php-wasm": "PHP (Wasm) Starter",
  "cpp": "C++ Starter",
  "cpp-wasm": "C++ (Wasm) Starter",
  "java": "Java Starter",
  "csharp-wasm": "C# (Wasm) Starter",
  "fsharp": "F# Starter",
  "fsharp-wasm": "F# (Wasm) Starter",
  "perl": "Perl Starter",
  "lua": "Lua Starter",
  "lua-wasm": "Lua (Wasm) Starter",
  "teal": "Teal Starter",
  "fennel": "Fennel Starter",
  "julia": "Julia Starter",
  "scheme": "Scheme Starter",
  "commonlisp": "Common Lisp Starter",
  "clojurescript": "ClojureScript Starter",
  "gleam": "Gleam Starter",
  "tcl": "Tcl Starter",
  "markdown": "Markdown Starter",
  "assemblyscript": "AssemblyScript Starter",
  "wat": "WebAssembly Text Starter",
  "sql": "SQL Starter",
  "postgresql": "PostgreSQL Starter",
  "prolog": "Prolog Starter",
  "minizinc": "MiniZinc Starter",
  "blockly": "Blockly Starter",
  "diagrams": "Diagrams Starter"
}