name: CI-test-schedule

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test-develop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        env:
          CI: true
      - name: e2e
        run: npm run e2e
        env:
          CI: true

  test-master:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
        env:
          CI: true
      # - name: e2e
      #   run: npm run e2e
      #   env:
      #     CI: true
