name: Deploy to FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: false
        default: "main"

env:
  NODE_VERSION: 24.x

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ secrets.FTP_HOST != '' }}
    env:
      NODE_OPTIONS: "--max_old_space_size=8192"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ${{ secrets.FTP_PROTOCOL }}
          local-dir: ./dist/
          server-dir: ${{ secrets.FTP_PATH }}
