name: Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            set -e
            cd livecodes
            git checkout main
            git pull origin main
            echo "${{ vars.VPS_ENV }}" > .env
            docker compose build
            docker compose up -d
            docker container prune -f
            docker image prune -a -f
